### ISSUE TITLE
Support FUNCTIONs and SUBs

### ISSUE THREAD

**Issue by flagxor** [google/wwwbasic#21]
This is needed to support a bunch of the qbasic programs like GORILLA.BAS + NIBBLES.BAS

**Comment by metaa** [comment]
I'm not experienced with BASIC, but QBASIC looks like an extension to BASIC I guess?

Maybe it would be wise to modularize the QBASIC specific code and make it two separate functions to allow explicitly running BASIC using the `.basic` function and QBASIC using `.qbasic`

```diff
   var basic = require('wwwbasic')
--   basic.Basic(`
++   basic.QBasic(`
   10 PRINT "HELLO WORLD"
   20 GOTO 10
   `)
```

**Comment by FellippeHeitor** [comment]
For Gorilla.bas to run as is, DEF FN should also be considered.

**Comment by hax** [comment]
Could we throw a error message for unimplemented feature now?

(When I see this project I'm excited because it make me recall my childhood, so I searched the source for GORILLA.BAS and try it, but just get the black screen with silence, make me a little frustrating :)

**Comment by FellippeHeitor** [comment]
@hax: Use QB64 until wwwbasic gets there :-)

**Comment by flagxor** [comment]
Yeah, would like to get this sorted soon.
It's a largish change as it adds call frames, but getting close.

DEF FN will be part of the same change.

**Comment by FellippeHeitor** [comment]
The only difference between a FUNCTION and an FN is scope, really, as DEF FN can access local variables. We haven't gotten it working in QB64 so far (we ship a slightly modified version of gorilla.bas that has DEF FN turned into FUNCTION to work).

**Comment by flagxor** [comment]
Implemented (roughly) in:
https://github.com/google/wwwbasic/commit/95489f94bc055a13a3c9eb357fe078d4d80bcf58

Will sort out any bugs in other issues.
