### ISSUE TITLE
Implement ON x GOTO a,b,c,d

### ISSUE THREAD

**Issue by flagxor** [google/wwwbasic#25]
This just needs the parsing and then add code gen to jump to the right label.

**Comment by pauwell** [comment]
Hello there!

I wrote an implementation for ON..GOTO:

```js
// ... line 1898
else if (tok == 'on') {
  Skip('on'); 
  var name = GetVar(); 
  Skip('goto');
  if(EndOfStatement()){
    Throw('Expected labels.');
  }
  curop += 'ip = labels[[';
  while (!(EndOfStatement())) { 
    curop += '\'' + String(tok) + '\'';
    Next();
    if(EndOfStatement()){
      curop += ']['+name+' - 1]];\n';
    }else{
      curop += tok;
      Skip(',');
    }
  }
  NewOp();
} 
// ...
```
### Example:
Input: 
```
x = 2
ON x GOTO a, b, c, d, e, f
```
Produces the following content for <code>curop</code>:
```
s[0>>2] = (((2)));
ip = labels[['a','b','c','d','e','f'][s[0>>2] - 1]];
```

Does this fit the style you intended? This my first time trying to contribute so please feel free to correct me on any mistake I did.

**Comment by flagxor** [comment]
Yes very close!
Would you be comfortable doing this as a pull request?

Few things:
* In the case the value is not in range, gwbasic mostly just keeps going to the next statement. You could handle this by generating:
ip = labels[[...][x-1] || ip;
(so if the label pulled out is undefined, it'll failover to the old value (ie the next block).

* Rather than GetVar() it should probably get GetExpression() as any expression can go there.

* It looks like its suppose to round down in the case the index is out of range. So you'll want something like:
curop += '][(('+name+')|0) - 1]];\n';

* A test in test/ would be nice, but I'll take the PR without.

* Bonus points for doing on gosub, which can probably share most of the same code.

**Comment by flagxor** [comment]
Send you an invite to colab. Once you accept, I can assign the issue to you. :-)
Welcome!

**Comment by pauwell** [comment]
Thanks a lot! 
I will add the changes and do a pull request today or tomorrow. 
Really looking forward to participate :)

**Comment by flagxor** [comment]
Implemented in:
https://github.com/google/wwwbasic/pull/32
