### ISSUE TITLE
A suggested bug-fix for the "swap" statement

### ISSUE THREAD

**Issue by CharlieJV** [google/wwwbasic#55]
As is, "swap a$, b$" will put the value of b$ in a$, then put a$ (which is now equal to b$) into b$ (i.e. leaving b$ as it was at the start.)

The fix to my version of the code (included in [BASIC Anywhere Machine](https://sites.google.com/view/basicanywheremachine), new release pending) has this line:

`        curop += b + ' = t' + ';\n';`

which replaces the following line in the version of wwwbasic.js currently on github:

`        curop += b + ' = ' + a + ';\n';`

**Comment by flagxor** [comment]
Thanks for catching!
I've fixed here and added a test:
https://github.com/google/wwwbasic/commit/4b17610b10f02e3f8c1ceb28545a745e1020ef61
