### ISSUE TITLE
using online ace editor

### ISSUE THREAD

**Issue by unitycoder** [google/wwwbasic#7]
has anyone added ace editor syntax highlight/definitions for this yet?
https://ace.c9.io/

would be nice to have online code playground for this..

**Comment by RandomGuyDTB** [comment]
Definitely agree that this would be helpful.

**Comment by flagxor** [comment]
Oh and, Thanks for the great suggestion!
(though as you say, no syntax file for BASIC it seems)

**Comment by flagxor** [comment]
Fortran seems the closest substitute they've got at the moment :-/
Doing that for now.
